dist: xenial
services: docker
language: python
python: "3.6"

env:
  global:
    - IMAGE_NAME=praekeltfoundation/junebug
    - REGISTRY_USER=praekeltorgdeploy
    - secure: "RZUwFFfrEKTv7Z/EAGQDJ/3LQWWutBpSCv+UFWvlQi/OjacN7scIR9rXBKfBxArHA/qh6XjU3DrZDGRfwOn9csDbhb7evDWG8XsAlWfK+TRRaWqCz2TlrJ3Ck+Oz7dZHRjAGvFi/dGPM6nF/MAvSe0iXgc38Apw7SPkHz68wr7kNZ7fSUo/jZd2Gp5l+PlSvp1jnK3vX3Nka0B1irLcINrlrWG1+BA7fnj324DOi1+DMuWg5HlJFF1FOTaBB1X1K5ULfUBtE2h5vmnxvUPLmLrLg2JBeDsQA6H4KanIj77ZZulHWKmzdf1VnJt8MnHc7LMP7JXBBYaJ1hfuqm8lzKNC062kWdfqS7YSN6cNlj2qtbVjW8XwnwNzxhvTC5M7D2lNJQ/R7iVvYXzKlbc01DeZ0uR3s4mY39smp0cWmhuQkd0u2u8HqG/KJCWVYw0Zupj1kkcEdJF0J0jxRF63JJATr/ENta27zhLw8eJqCNoukRx/feMR36Ikd+wo6mXx/t3WXjkF9okVh0hJNZayvE3oXLgB81SKw8E+AVFRmlo7AoCkKPH3CnF3KQVuVhiThbQLdqgtxToQ+o/xybpsH0PAx2JPNMLbTx8VWqpDUZtqgCN+CqXw4HVwrRAo/v1iDWm9ILUvpO+564BZ97g9Kz4IV1jdORDPi9nnXZUKk23Y="

before_install:
  - pip install -U pip
install:
  - pip install -r seaworthy/requirements.txt

before_script:
  - version="$(sed -nE 's/^junebug==([0-9\.]+)/\1/p' requirements.txt)"
  - echo "Building image '$IMAGE_NAME' for Junebug version '$version'..."
  - docker pull "$IMAGE_NAME" || true
script:
  - docker build --pull --cache-from "$IMAGE_NAME" -t "$IMAGE_NAME" .
  - pytest -v seaworthy/test.py --duration=10 --junebug-image="$IMAGE_NAME"
after_script:
  - docker images

before_deploy:
  - pip install docker-ci-deploy==0.3.0
  - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
deploy:
  provider: script
  script: dcd --version "$version" --version-latest --version-semver "$IMAGE_NAME"
  on:
    branch: master
