dist: xenial
services: docker
language: python
python: "3.6"

env:
  global:
    - IMAGE_NAME=praekeltfoundation/junebug
    - REGISTRY_USER=praekeltorgdeploy
    - secure: "AyPSlg6sXxdWGOuJDCPd1sn17tB+qAfYcFbmRysm8A8d4bN0JY2z4EhrGChMkiMZ4p5FHX7Pg5j5eISsEa54j35FgADxlP3jHh/XuahoCIoLrgLLVD2VrrcOI+epyQ+UgMAbLmBu0wQ3gX7g237YoJLKXViZ4vFbVTlOJ//T0XACZ1s2mtiU9dCsV4dXlXb2IgsE+olkuUSWnBFHEBbSXCjGDvQvY8pTtqS/3AIuFK4/C4ZgjeEZRGsfwp4tgcGSq9o9adNIcep+yLoEz9Sd/K+L86xw+Uj2mgA2PCPhUj1FqYJWo03iKW3UwAsvEy3uae1kOQw6KVzLRHUFTW5k7WJm3xA1pilluv7BEJxB1PcZ6p1eh4qMHBWiEpfgqKjWPqNblbxSt3oL39DUvTQCSM0pdphArRBT9gXm3HdAuyLCUkPplx0Vq415wQtqirV8P7grSIjo1ROpVXgUcWvCb8D0dcpzjOAWpMDSYtaOYhwjue0OXvSbMSChKSzKsGVRIzLS3zv9FkNObaf/SO4xULOYx+ucWZp9i+8pi4OGNelRTIMPAC71ImhZ4YSVmZ7WrJX/9gvVCxepEagK6UO/ZL1NOzHEddGYRAlolANKe57Cx4FMW0TtxEHL4DsUoCqp3w3EUvbTICVw1TB/qWhIkK4P05tv0F3Fk0MJcmU9q3Y="

before_install:
  - pip install -U pip
install:
  - pip install -r seaworthy/requirements.txt

before_script:
  - version="$(sed -nE 's/^junebug==([0-9\.]+)/\1/p' requirements.txt)"
  - echo "Building image '$IMAGE_NAME' for Junebug version '$version'..."
  - docker pull "$IMAGE_NAME" || true
script:
  - docker build --pull --cache-from "$IMAGE_NAME" -t "$IMAGE_NAME" .
  - pytest -v seaworthy/test.py --duration=10 --junebug-image="$IMAGE_NAME"
after_script:
  - docker images

before_deploy:
  - pip install docker-ci-deploy==0.3.0
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: dcd --version "$version" --version-latest --version-semver "$IMAGE_NAME"
  on:
    branch: master
