#!/bin/bash -e

export NGINX_FILE="/etc/supervisor/conf.d/nginx.conf"
export HTPASSWD_FILE="/etc/supervisor/conf.d/htpasswd"
export AUTH_BASIC="off"

if [ -n "$AUTH_USERNAME" ] && [ -n "$AUTH_PASSWORD" ]; then
    AUTH_BASIC="\"Junebug\""
    AUTH_PASSWORD_CRYPT="$(echo $AUTH_PASSWORD | openssl passwd -crypt -stdin)"
    echo "$AUTH_USERNAME:{crypt}$AUTH_PASSWORD_CRYPT:generated by nginx-entrypoint.sh" > $HTPASSWD_FILE
fi

cat > $NGINX_FILE <<EOF
location /jb/ {
  auth_basic ${AUTH_BASIC};
  auth_basic_userfile ${HTPASSWD_FILE};
  proxy_pass http://127.0.0.1:8080/;
}
EOF

nginx -g "daemon off;"
