#!/bin/bash -e

NGINX_FILE="./nginx.conf"
HTPASSWD_FILE="./htpasswd"
AUTH_BASIC="off"
JUNEBUG_INTERFACE=${JUNEBUG_INTERFACE:-0.0.0.0}
JUNEBUG_PORT=${JUNEBUG_PORT:-8080}

if [ -n "$AUTH_USERNAME" ] && [ -n "$AUTH_PASSWORD" ]; then
    AUTH_BASIC="\"Junebug\""
    AUTH_PASSWORD_CRYPT="$(echo $AUTH_PASSWORD | openssl passwd -crypt -stdin)"
    echo "$AUTH_USERNAME:{crypt}$AUTH_PASSWORD_CRYPT:generated by nginx-entrypoint.sh" > $HTPASSWD_FILE
else
    cat <<EOF
*************************************************************
*                                                           *
*                           WARNING!                        *
*                                                           *
*         Running Junebug without authentication is         *
*                     A REALLY BAD IDEA.                    *
*                                                           *
*         Set the AUTH_USERNAME and AUTH_PASSWORD           *
*         environment variables to enable HTTP              *
*         Basic Authentication and make sure to             *
*         only offer this service over TLS                  *
*                                                           *
*************************************************************
EOF
fi

cat > $NGINX_FILE <<EOF
location /jb/ {
  auth_basic ${AUTH_BASIC};
  auth_basic_userfile ${HTPASSWD_FILE};
  proxy_pass "http://${JUNEBUG_INTERFACE}:${JUNEBUG_PORT}/";
}
EOF

exec nginx -g "daemon off;"
